apiVersion: v1
kind: Service
metadata:
  labels:
    io.wger.service: cache
  name: cache
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    io.wger.service: cache
status:
  loadBalancer: {}
