apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.wger.service: cache
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.wger.service: cache
  strategy: {}
  template:
    metadata:
      labels:
        io.wger.service: cache
    spec:
      containers:
      - image: redis:latest
        imagePullPolicy: "IfNotPresent"
        name: cache
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      #volumes: null
status: {}
