apiVersion: v1
kind: Service
metadata:
  labels:
    io.wger.service: db
  name: db
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.wger.service: db
status:
  loadBalancer: {}
