apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.wger.service: media
  name: media
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: "media"
# status: {}
