apiVersion: v1
data:
  DJANGO_CACHE_BACKEND: django_redis.cache.RedisCache
  DJANGO_CACHE_CLIENT_CLASS: django_redis.client.DefaultClient
  DJANGO_CACHE_LOCATION: redis://cache:6379/1
  DJANGO_CACHE_TIMEOUT: "1300000"
  DJANGO_DB_DATABASE: wger
  DJANGO_DB_ENGINE: django.db.backends.postgresql
  DJANGO_DB_HOST: db
  DJANGO_DB_PASSWORD: wger
  DJANGO_DB_PORT: "5432"
  DJANGO_DB_USER: wger
  DJANGO_DEBUG: "False"
  WGER_USE_GUNICORN: "True"
kind: ConfigMap
metadata:
  labels:
    io.wger.service: web-prod-env
  name: prod-env
