apiVersion: v1
kind: Service
metadata:
  labels:
    io.wger.service: web
  name: web
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    io.wger.service: web
status:
  loadBalancer: {}
